### ISSUE TITLE
about show_3D

### ISSUE THREAD

**Issue by www04576** [DeclK/3d-object-vis#1]
Hi @DeclK , thank you so much for sharing such a nice work. 
I follow your instruction to use inference.py to process data from kitti raw data, and it works well.
But when I try to display my point cloud data continuously, I set **interactive = False** in show_3D function like this
`
self.vi.show(self.actors + self.actors_without_del,
                     camera=dict(pos=[-20, 0, 5], viewup=[0, 0, 1], focalPoint=[50, 0, 2], viewAngle=45),
                     q=False, axes=4, rate=10, interactive=True, mode=0)
`
However, there is an obvious vedo window opening animation that makes the display process very unsmooth. I can't make it like your display in your vedio.
Could you help me fix it? Thank you very much!

**Comment by www04576** [comment]
btw, when I run inference.py I have to create a new empty result.pkl file to hold the result, otherwise there will be a file not found error. Do you have some good idea?

**Comment by DeclK** [comment]
I don't quite get your first question. The demo video was made by consecutive frames. I used ffmpeg to convert these frames to mp4. And you are right, you need to create a `.pkl` before running `inference.py`. I will modify this part of code to solve such issue👍

**Comment by www04576** [comment]
@DeclK thank you for your method! I successfully solved my problem.
