### ISSUE TITLE
3d object vis on once

### ISSUE THREAD

**Issue by andy690** [DeclK/3d-object-vis#2]
Hi @DeclK , thank you so much for sharing such a nice work.

I tried to apply this project to once, but maybe it's a matter of parameter selection. Once can't all be visualized, and its angle is very uncomfortable. Do you have a similar attempt and can you share your settings?

**Comment by DeclK** [comment]
I'm not quite clear about your questions🤣. I tried to visualize ONCE before, and it worked fine. The basic idea of this project is to visualize any pointcloud dataset according to a 2-D tensor (N, 3)

I think you might need to adjust the `show_3D` function which controls the camera settings
https://github.com/DeclK/3d-object-vis/blob/d278484fb814f321f709fdd6909b9d21e388bea8/viewer/viewer.py#L401-L413

The params here means the camera is located at (0, 0, 150) which is a very high position, and it attempts to take a BEV photo of the scene. You can moidfy settings here to meet your requirements
